# Generated by Django 5.1.1 on 2024-09-12 19:12

import django.core.validators
import django.db.models.deletion
import user_comments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_name",
                    models.CharField(
                        max_length=255,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9a-zA-Z]*$",
                                "Only alphanumeric characters are allowed.",
                            )
                        ],
                        verbose_name="User Name",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        validators=[
                            django.core.validators.EmailValidator(
                                message="Enter a valid email address."
                            )
                        ],
                        verbose_name="E-mail",
                    ),
                ),
                (
                    "home_page",
                    models.URLField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.URLValidator()],
                        verbose_name="Home page",
                    ),
                ),
                (
                    "captcha",
                    models.CharField(
                        max_length=6,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9a-zA-Z]*$",
                                "Only alphanumeric characters are allowed.",
                            )
                        ],
                        verbose_name="CAPTCHA",
                    ),
                ),
                ("text", models.TextField(verbose_name="Comment Text")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="comment_images/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "png", "gif"]
                            )
                        ],
                        verbose_name="Image",
                    ),
                ),
                (
                    "text_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="comment_files/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["txt"]
                            ),
                            user_comments.models.validate_file_size,
                        ],
                        verbose_name="Text File",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="user_comments.comment",
                        verbose_name="Parent Comment",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
