# Generated by Django 5.1.1 on 2024-09-15 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_comments", "0002_userinfo_alter_comment_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="parent",
            new_name="parent_comment",
        ),
    ]
